version: '3'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-docker-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gfgmicroservicesdemo
    ports:
      - "3306:3306"

  address-service:
    image: address-service-latest
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8081:8081"
