version: '3'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-docker-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gfgmicroservicesdemo
    ports:
      - "3306:3306"
    healthcheck:
      test: curl --fail http://mysql-docker-container:3306/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3

  address-service:
    image: address-service-latest
    depends_on:
      - mysql-db
      - employee-service
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8081:8081"

  employee-service:
    image: employee-service-latest
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8080:8080"
