apiVersion: apps/v1
kind: Deployment
metadata:
  name: address
spec:
  replicas: 2
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
        - name: address-service
          image: address-service:2.0
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: address-service
spec:
  selector:
    app: address
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
